# Twig Configuration
twig:
    globals:
      navi_brands: "%navi_brands%"
      url_activate: "http://localhost/fafa/web/app_dev.php/me/activate"
      app_web_name: "%app_web_name%"    
      navi_user_home: "%navi_user_home%"
      navi_user_feed: "%navi_user_feed%"
      navi_user_message: "%navi_user_message%"
      navi_user_auto: "%navi_user_auto%"
      navi_user_blog: "%navi_user_blog%"
      navi_user_comment: "%navi_user_comment%"
      navi_user_comy: "%navi_user_comy%"
      navi_user_album: "%navi_user_album%"
      navi_user_settings: "%navi_user_settings%"
      navi_user_my_cars: "%navi_user_my_cars%"
      navi_user_car: "%navi_user_car%"
      navi_user_my_account: "%navi_user_my_account%"
      navi_user_guests: "%navi_user_guests%"
      navi_user_bookmark: "%navi_user_bookmark%"
      navi_user_log_out: "%navi_user_log_out%"
      navi_user_edit_account: "%navi_user_edit_account%"
      navi_user_black_list: "%navi_user_black_list%"
      navi_user_follow_user: "%navi_user_follow_user%"
      navi_user_follow_car: "%navi_user_follow_car%"
      navi_user_follow_car_new: "%navi_user_follow_car_new%"
      navi_user_m_balance: "%navi_user_m_balance%"
      navi_user_m_spend: "%navi_user_m_spend%"
      navi_user_m_buy: "%navi_user_m_buy%"
      navi_user_help: "%navi_user_help%"
      navi_user_top_local: "%navi_user_top_local%"
      navi_user_top_world: "%navi_user_top_world%"
      navi_user_top_logs: "%navi_user_top_logs%"
      navi_user_top_blogs: "%navi_user_top_blogs%"
      navi_user_autos_cat: "%navi_user_autos_cat%"
      navi_user_autos_random: "%navi_user_autos_random%"
      navi_user_my_pro: "%navi_user_my_pro%"
      navi_user_mails: "%navi_user_mails%"
      navi_user_admin: "%navi_user_admin%"
      navi_foot_help: "%navi_foot_help%"
      navi_foot_licence: "%navi_foot_licence%"
      navi_foot_project: "%navi_foot_project%"
      navi_foot_about_us: "%navi_foot_about_us%"
      navi_foot_impressum: "%navi_foot_impressum%"
      navi_foot_agb: "%navi_foot_agb%"
      title_block_blogs_new: "%title_block_blogs_new%" 
      title_block_cars_new: "%title_block_cars_new%"    
      title_block_carlogs_new: "%title_block_carlogs_new%"  
      title_block_comyblog_new:  "%title_block_comyblog_new%"
      page_head_wellcome: "%page_head_wellcome%" 
      page_head_slogan: "%page_head_slogan%"
      page_head_users: "%page_head_users%"
      page_head_cars: "%page_head_cars%"
      page_head_carlogs: "%page_head_carlogs%"
      page_head_blogs: "%page_head_blogs%"
      page_head_feed_cars: "%page_head_feed_cars%"
      page_head_comments: "%page_head_comments%"
      page_head_comments_new: "%page_head_comments_new%"
      page_head_comment_new: "%page_head_comment_new%"
      page_head_comys: "%page_head_comys%"
      page_head_comy: "%page_head_comy%"
      page_head_comyforums: "%page_head_comyforums%"
      page_head_comyblogs: "%page_head_comyblogs%"
      page_head_comyblog_new: "%page_head_comyblog_new%"
      page_head_comyforum_new: "%page_head_comyforum_new%"
      page_head_geust_my: "%page_head_geust_my%"
      page_head_bookmark: "%page_head_bookmark%"
      page_head_bookmark_my: "%page_head_bookmark_my%"
      page_head_change_email: "%page_head_change_email%"
      page_head_change_pwd: "%page_head_change_pwd%"
      page_head_comm_my_last: "%page_head_comm_my_last%"
      page_head_comm_to_me: "%page_head_comm_to_me%"
      page_head_change_login: "%page_head_change_login%"
      page_head_black_list_manage: "%page_head_black_list_manage%"
      page_head_car_follow: "%page_head_car_follow%"
      page_head_user_follow: "%page_head_user_follow%"
      page_head_me_follow: "%page_head_me_follow%"
      page_head_brands: "%page_head_brands%"
      info_wellcome1: "%info_wellcome1%"
      info_wellcome2: "%info_wellcome2%" 
      info_car_most_visited: "%info_car_most_visited%"
      info_ctrl_enter: "%info_ctrl_enter%"
      info_ctrl_save_send: "%info_ctrl_save_send%"
      info_search_quick: "%info_search_quick%"
      info_user_about: "%info_user_about%"
      info_user_ex_autos: "%info_user_ex_autos%"
      info_user_reg_from: "%info_user_reg_from%"    
      info_user_comment: "%info_user_comment%"
      info_comm_count: "%info_comm_count%"
      info_comm_new: "%info_comm_new%"
      info_comm_black_list: "%info_comm_black_list%"
      info_img_size: "%info_img_size%"
      info_comm_colors: "%info_comm_colors%"
      info_guest_last_on: "%info_guest_last_on%"
      info_guest_count: "%info_guest_count%" 
      info_mess_select_chat: "%info_mess_select_chat%"
      info_comy_rule: "%info_comy_rule%"
      info_car_platenr: "%info_car_platenr%"
      info_car_motor: "%info_car_motor%"
      info_car_yearprod: "%info_car_yearprod%"
      info_car_yearbuy: "%info_car_yearbuy%"
      info_offline_comm: "%info_offline_comm%"
      but_next: "%but_next%"
      but_login: "%but_login%"
      but_registration: "%but_registration%"
      but_activate: "%but_activate%"
      but_show_more: "%but_show_more%"
      but_sort_asc: "%but_sort_asc%"
      but_sort_desc: "%but_sort_desc%"
      but_car_new: "%but_car_new%"
      but_edit: "%but_edit%"
      but_remove: "%but_remove%"
      but_delete: "%but_delete%"
      but_remove_def: "%but_remove_def%"
      but_open: "%but_open%"
      but_confirm: "%but_confirm%"
      but_new_blog: "%but_new_blog%"
      but_save: "%but_save%"
      but_selection: "%but_selection%"
      but_send: "%but_send%"
      but_add_apicture: "%but_add_apicture%"
      but_delete_history: "%but_delete_history%"
      but_reply: "%but_reply%"
      but_like: "%but_like%"
      but_like_no: "%but_like_no%"
      but_liked: "%but_liked%"
      but_follow: "%but_follow%"
      but_follow_no: "%but_follow_no%"
      but_follow_i: "%but_follow_i%"
      but_follow_i_no: "%but_follow_i_no%"
      but_follow_dead: "%but_follow_dead%"
      but_follow_dead_no: "%but_follow_dead_no%"
      but_follow_dead_i: "%but_follow_dead_i%"
      but_follow_dead_i_no: "%but_follow_dead_i_no%"
      but_follow_me: "%but_follow_me%"
      but_follow_i_user1: "%but_follow_i_user1%"
      but_follow_i_user2: "%but_follow_i_user2%"
      but_follow_i_user3: "%but_follow_i_user3%"
      but_follow_i_car1: "%but_follow_i_car1%"
      but_follow_i_car2: "%but_follow_i_car2%"
      but_follow_i_car3: "%but_follow_i_car3%"
      but_follow_me1: "%but_follow_me1%"
      but_follow_me2: "%but_follow_me2%"
      but_follow_me3: "%but_follow_me3%"
      but_message: "%but_message%"
      but_new_carlog: "%but_new_carlog%"
      but_kult: "%but_kult%"
      but_cars: "%but_cars%"
      but_user: "%but_user%"
      but_blogs: "%but_blogs%"
      but_logbooks: "%but_logbooks%"
      but_new_blogs: "%but_new_blogs%"
      but_black_in: "%but_black_in%"
      but_black_in_anyway: "%but_black_in_anyway%"
      but_black_out_anyway: "%but_black_out_anyway%"
      but_black_out: "%but_black_out%"
      but_sure: "%but_sure%"
      but_done: "%but_done%"
      but_read_more: "%but_read_more%"
      but_done: "%but_done%"
      but_img_crop: "%but_img_crop%"
      but_hide: "%but_hide%"
      but_bookmarks: "%but_bookmarks%"
      but_model_all: "%but_model_all%"
      but_leave: "%but_leave%"
      but_invite: "%but_invite%"
      but_member: "%but_member%"
      but_member: "%but_member%"
      but_comy_new: "%but_comy_new%"
      but_comyblog_new: "%but_comyblog_new%"
      but_comyforum_new: "%but_comyforum_new%"
      but_show_comyblogs_all: "%but_show_comyblogs_all%"
      but_show_comyforums_all: "%but_show_comyforums_all%"
      but_info_more: "%but_info_more%"
      but_edit: "%but_edit%"
      field_label_login_data: "%field_label_login_data%"
      field_label_activation_code: "%field_label_activation_code%"
      field_label_lname: "%field_label_lname%"
      field_label_fname: "%field_label_fname%"
      field_label_account_picture: "%field_label_account_picture%"
      field_label_drive_car_since: "%field_label_drive_car_since%"
      field_label_login: "%field_label_login%"
      field_label_email: "%field_label_email%"
      field_label_pwd: "%field_label_pwd%"
      field_label_pwd_again: "%field_label_pwd_again%"
      field_label_gender: "%field_label_gender%"
      field_label_hidename: "%field_label_hidename%"
      field_label_phone: "%field_label_phone%"
      field_label_dborn: "%field_label_dborn%"
      field_label_hideborn: "%field_label_hideborn%"
      field_label_hideage: "%field_label_hideage%"
      field_label_country: "%field_label_country%"
      field_label_city: "%field_label_city%"
      field_label_selfi: "%field_label_selfi%"
      field_label_selfi_tip: "%field_label_selfi_tip%"
      field_label_avatar: "%field_label_avatar%"
      field_label_avatar_tip: "%field_label_avatar_tip%"
      field_label_about: "%field_label_about%"
      field_label_drivestart: "%field_label_drivestart%"
      field_label_old_email: "%field_label_old_email%"
      field_label_new_email: "%field_label_new_email%"
      field_label_old_login: "%field_label_old_login%"
      field_label_new_login: "%field_label_new_login%"
      field_label_old_password: "%field_label_old_password%"
      field_label_new_pwd: "%field_label_new_pwd%"
      field_label_new_pwd_again: "%field_label_new_pwd_again%"
      field_label_user_mention: "%field_label_user_mention%"
      field_label_link: "%field_label_link%"
      field_label_please_enter_here_the_url: "%field_label_please_enter_here_the_url%"
      field_label_please_enter_here_the_title: "%field_label_please_enter_here_the_title%"
      field_label_ajust_video: "%field_label_ajust_video%"
      field_label_edited_on: "%field_label_edited_on%"
      field_label_show_all: "%field_label_show_all%"
      field_label_foto_upload: "%field_label_foto_upload%"
      field_label_keep_signed: "%field_label_keep_signed%"
      field_label_plate_show: "%field_label_plate_show%"
      field_label_power: "%field_label_power%"
      field_label_displacement: "%field_label_displacement%"
      field_label_area: "%field_label_area%"
      field_label_about_what: "%field_label_about_what%"
      field_label_created_on: "%field_label_created_on%"
      field_label_mileage: "%field_label_mileage%"
      field_label_price: "%field_label_price%"
      field_label_allowcomment: "%field_label_allowcomment%"
      field_label_yearprod: "%field_label_yearprod%"
      field_label_yearbuy: "%field_label_yearbuy%"
      field_label_plate: "%field_label_plate%"
      field_label_vehicle_data: "%field_label_vehicle_data%"
      field_label_brand: "%field_label_brand%"
      field_label_model: "%field_label_model%"
      field_label_gen: "%field_label_gen%"
      field_label_color: "%field_label_color%"
      field_label_car_title: "%field_label_car_title%"
      field_label_additional_text: "%field_label_additional_text%"
      field_label_actually: "%field_label_actually%"
      field_label_previous: "%field_label_previous%"
      field_label_description: "%field_label_description%"
      field_label_status: "%field_label_status%"
      field_label_vin: "%field_label_vin%"
      field_label_text: "%field_label_text%"
      field_label_title: "%field_label_title%"
      field_label_comm_4_invite: "%field_label_comm_4_invite%"
      field_label_agb: "%field_label_agb%"
      field_label_foto_tip: "%field_label_foto_tip%"
      field_label_rule: "%field_label_rule%"
      field_label_notify_comnew: "%field_label_notify_comnew%"
      field_label_notify_messnew: "%field_label_notify_messnew%"
      field_label_notify_readernew: "%field_label_notify_readernew%"
      tip_car_remove: "%tip_car_remove%"
      tip_blog_remove: "%tip_blog_remove%"
      tip_carlog_remove: "%tip_carlog_remove%"
      tip_comy_remove: "%tip_comy_remove%"
      tip_comyblog_remove: "%tip_comyblog_remove%"
      tip_comyforum_remove: "%tip_comyforum_remove%"
      tip_black_list_in: "%tip_black_list_in%"
      tip_mess_hide: "%tip_mess_hide%"
      tip_mess_remove: "%tip_mess_remove%"
      tip_offline: "%tip_offline%"
      tip_like_users_load: "%tip_like_users_load%"
      valid_no_access: "%valid_no_access%"
      valid_activate_error: "%valid_activate_error%"
      valid_pwd: "%valid_pwd%"
      valid_pwd_wrong: "%valid_pwd_wrong%"
      valid_reg_login_exist: "%valid_reg_login_exist%"
      valid_reg_email_exist: "%valid_reg_email_exist%"
      valid_user_dir_rename_no: "%valid_user_dir_rename_no%"
      valid_changes_or: "%valid_changes_or%"
      valid_changes_ok: "%valid_changes_ok%"
      valid_changes_ok_goto_profile: "%valid_changes_ok_goto_profile%"
      valid_changes_ok_goto_forum: "%valid_changes_ok_goto_forum%"
      valid_changes_ok_goto_comyblog: "%valid_changes_ok_goto_comyblog%"
      valid_comm_mark_as_read_ok: "%valid_comm_mark_as_read_ok%"
      valid_comm_mark_as_read_no: "%valid_comm_mark_as_read_no%"
      valid_changes_ok_goto_comy: "%valid_changes_ok_goto_comy%"
      valid_changes_ok_goto_carlog: "%valid_changes_ok_goto_carlog%"
      valid_changes_ok_goto_car: "%valid_changes_ok_goto_car%"
      valid_changes_ok_goto_blog: "%valid_changes_ok_goto_blog%"
      valid_foto_upload_user_only: "%valid_foto_upload_user_only%"
      valid_foto_typ_wrong: "%valid_foto_typ_wrong%"
      valid_foto_size_min_width: "%valid_foto_size_min_width%"
      valid_foto_size_min_height: "%valid_foto_size_min_height%"
      valid_foto_size_max: "%valid_foto_size_max%"
      valid_foto_resize_err: "%valid_foto_resize_err%"
      valid_foto_no_file: "%valid_foto_no_file%"
      valid_comm_mark_as_read_user_wrong: "%valid_comm_mark_as_read_user_wrong%"
      valid_mail_send_deactivated: "%valid_mail_send_deactivated%"
      valid_comy_member_not: "%valid_comy_member_not%"
      valid_mail_send_not: "%valid_mail_send_not%"
      valid_mail_comy_invite_send_ok: "%valid_mail_comy_invite_send_ok%"
      title_blog_last_visited: "%title_blog_last_visited%"
      title_carlog_last_visited: "%title_carlog_last_visited%"
      title_user_activation: "%title_user_activation%"
      title_user_activation_ok: "%title_user_activation_ok%"
      title_user_login_data: "%title_user_login_data%"
      title_comments_to_me: "%title_comments_to_me%"
      title_comments_my: "%title_comments_my%"
      title_block_blogs_new: "%title_block_blogs_new%"
      title_block_cars_new: "%title_block_cars_new%"
      title_block_carlogs_new: "%title_block_carlogs_new%"
      title_block_comyblog_new: "%title_block_comyblog_new%"
      title_car_about: "%title_car_about%"
      title_user_count: "%title_user_count%"
      title_help_head: "%title_help_head%"
      title_comy_comms_new: "%title_comy_comms_new%"
      title_comy_member: "%title_comy_member%"
      title_car_reg: "%title_car_reg%"
      title_home_act_1: "%title_home_act_1%"
      title_home_act_2: "%title_home_act_2%"
      title_home_act_3: "%title_home_act_3%"
      title_home_act_4: "%title_home_act_4%"
      title_home_act_5: "%title_home_act_5%"
      help_bookmark: "%help_bookmark%"
      help_black: "%help_black%"
      help_geust: "%help_geust%"
      help_car_follow: "%help_car_follow%" 
      help_user_follow: "%help_user_follow%"
      help_me_follow: "%help_me_follow%"
      help_my_car_follow: "%help_my_car_follow%"
      help_home_act_1: "%help_home_act_1%"
      help_home_act_2: "%help_home_act_2%"
      help_home_act_3: "%help_home_act_3%"
      help_home_act_4: "%help_home_act_4%"
      help_home_act_5: "%help_home_act_5%"
    