# app/config/security.yml  
security:
    encoders:
        AppBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_EDITOR]
        
    providers:
        user_db:
            entity: { class: "AppBundle:User" }
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: /.*
            provider: user_db
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                use_referer: true
            logout:
                path: /logout
                target: /
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path: /.*

    access_control:
          #- { path: ^/admin, roles: ROLE_ADMIN }
          #- { path: /me/activate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          #- { path: /me/profile/real, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          #- { path: /me/profile, roles: ROLE_USER }
          #- { path: /test, roles: IS_AUTHENTICATED_ANONYMOUSLY }          
          - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          
